CLASS zif_zabap_toc_version DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    CONSTANTS:
        c_version TYPE string VALUE '1.3.0'.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zif_zabap_toc_version IMPLEMENTATION.
ENDCLASS.
